# These shortcuts do not depend on a personal gitconfig.
alias g='git'
alias gco='git commit'
alias gfe='git fetch --all --tags --prune'
alias gps='git push'
alias gpl='git pull --ff-only'
alias gst='git status -sb'
alias gaa='git add .'
alias gbr='git branch'
alias gif='git diff'
